### ISSUE TITLE
ch3 Test Failing

### ISSUE THREAD

**Issue by dkhermann** [PacktPublishing/Full-Stack-React-Projects-Third-Edition#88]
I am having issues with running the test in ch3.  Even though running the example.js works with createPost() the test is failing. 
Here is my code:
---
import mongoose from "mongoose";
import { describe, expect, test } from "@jest/globals";
import { createPost } from "../services/posts.js";
//import { Post } from "../db/models/post.js";
import { Post } from "../db/models/posts.js";

describe("creating posts", () => {
  test("with all parameters should succeed", async () => {
    const post = {
      title: "Hello Mongoose!",
      author: "Daniel Bugl",
      contents: "This post is stored in a MongoDB database using Mongoose.",
      tags: ["mongoose", "mongodb"],
    };
    const createdPost = await createPost(post);
    expect(createdPost._id).toBeInstanceOf(mongoose.Types.ObjectId);
    const foundPost = await Post.findById(createdPost._id);
    expect(foundPost).toEqual(expect.objectContaining(post));
    expect(foundPost.createdAt).toBeInstanceOf(Date);
    expect(foundPost.updatedAt).toBeInstanceOf(Date);
  });
});
---

here is the npm test output
> ch1@0.0.0 test
> NODE_OPTIONS=--experimental-vm-modules jest

(node:64769) ExperimentalWarning: VM Modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
 FAIL  src/test/posts.test.js (5.829 s)
  creating posts
    ✕ with all parameters should succeed (5004 ms)

  ● creating posts › with all parameters should succeed

    thrown: "Exceeded timeout of 5000 ms for a test.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

       9 |     done();
      10 |   });
    > 11 |   test("with all parameters should succeed", async () => {
         |   ^
      12 |     const post = {
      13 |       title: "Hello Mongoose!",
      14 |       author: "Daniel Bugl",

      at test (src/test/posts.test.js:11:3)
      at describe (src/test/posts.test.js:7:1)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        5.876 s, estimated 6 s
Ran all test suites.
Jest did not exit one second after the test run has completed.

'This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.

-----------------------------------------------------
I tried extending the timeout, but that does not work.  I am at a loss as to how to get this to work.  Any input would be greatly appreciated.

**Comment by omnidan** [comment]
Hi @dkhermann! First of all, sorry for my delayed response.

A timeout in this kind of test sounds like a database connection problem to me. Can you please make sure that the Docker container for the MongoDB database is running properly and reachable via the configured URL?

**Comment by omnidan** [comment]
Closing this due to inactivity, please feel free to reopen it with more information if you are still having this issue ☺️
